"""update borrowed book table 2

Revision ID: cec39adf8d2d
Revises: ff85e6dc0b08
Create Date: 2024-07-14 14:08:18.797601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cec39adf8d2d'
down_revision: Union[str, None] = 'ff85e6dc0b08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrowed_books', sa.Column('issued_by', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.create_foreign_key(None, 'borrowed_books', 'user', ['issued_by'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'borrowed_books', type_='foreignkey')
    op.drop_column('borrowed_books', 'issued_by')
    # ### end Alembic commands ###
