"""borrowed book table

Revision ID: df011cdcc156
Revises: 3294dafdaba9
Create Date: 2024-07-14 13:21:14.070717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df011cdcc156'
down_revision: Union[str, None] = '3294dafdaba9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('borrowed_books',
    sa.Column('user_uid', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('book_isbn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('issue_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['book_isbn'], ['book.isbn'], ),
    sa.ForeignKeyConstraint(['user_uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('user_uid', 'book_isbn')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('borrowed_books')
    # ### end Alembic commands ###
