"""update borrowed book table

Revision ID: ff85e6dc0b08
Revises: df011cdcc156
Create Date: 2024-07-14 14:04:18.813347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ff85e6dc0b08'
down_revision: Union[str, None] = 'df011cdcc156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrowed_books', sa.Column('is_returned', sa.Boolean(), nullable=False))
    op.alter_column('borrowed_books', 'return_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('borrowed_books', 'return_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_column('borrowed_books', 'is_returned')
    # ### end Alembic commands ###
